
name: CI

on:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: checkout
        uses: actions/checkout@v1

      - name: pester tests
        shell: pwsh
        run: |
          if (-not (Get-Module -ListAvailable Pester)) {
            Write-Output "Pester module not found, INSTALLING..."
            Install-Module Pester -Force
          }
          ./tests/GitHubActions_tests.ps1

      - name: publish to myget
        shell: pwsh
        run: |
          $nugetApiKey   = $env:MYGET_NUGET_API_KEY
          $nugetApiKeySS = ConvertTo-SecureString $nugetApiKey -AsPlainText
          $nugetCred     = [pscredential]::new('ignored', $nugetApiKeySS)
          Register-PSRepository -Name myget -Credential $nugetCred `
            -SourceLocation https://www.myget.org/F/pwsh-github-action-tools/api/v2 `
            -PublishLocation https://www.myget.org/F/pwsh-github-action-tools/api/v2/package
          
          Publish-Module -Path ./GitHubActions -Repository myget -NuGetApiKey $nugetApiKey
        env:
          MYGET_NUGET_API_KEY: ${{ secrets.MYGET_NUGET_API_KEY }}
